# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node3D

const HENGO_DEBUG_SCRIPT_ID = &'8822816724386196260'

var ammo = 30  
var mag = 30  
var score = 0  
var hit_ball = null  
var burst_left = 0  
var empty_reload = false  
 
var click_on_203_23: bool = false
var clicked_203_23: bool = false
var key_on_130_23: bool = false
var key_hit_130_23: bool = false
var key_on_138_23: bool = false
var key_hit_138_23: bool = false
var click_on_145_23: bool = false
var clicked_145_23: bool = false
var click_on_154_23: bool = false
var clicked_154_23: bool = false
var click_on_210_26: bool = false
var clicked_210_26: bool = false
var key_on_130_26: bool = false
var key_hit_130_26: bool = false
var key_on_138_26: bool = false
var key_hit_138_26: bool = false
var click_on_145_26: bool = false
var clicked_145_26: bool = false
var click_on_154_26: bool = false
var clicked_154_26: bool = false
var key_on_130_29: bool = false
var key_hit_130_29: bool = false
var key_on_138_29: bool = false
var key_hit_138_29: bool = false
var click_on_145_29: bool = false
var clicked_145_29: bool = false
var click_on_154_29: bool = false
var clicked_154_29: bool = false
var tween_66: Tween = null
var _mc_23_label = 'SEMI'
var _mc_23_rounds = 30
var _mc_26_label = 'BURST'
var _mc_26_rounds = 30
var _mc_29_label = 'AUTO'
var _mc_29_rounds = 30

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		armed=Armed.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("armed")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func _input(event: InputEvent) -> void:
	if click_on_203_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed and not event.double_click:
			clicked_203_23 = true
	if key_on_130_23 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_130_23 = true
	if key_on_138_23 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_138_23 = true
	if click_on_145_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_145_23 = true
	if click_on_154_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_154_23 = true
	if click_on_210_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed and not event.double_click:
			clicked_210_26 = true
	if key_on_130_26 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_130_26 = true
	if key_on_138_26 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_138_26 = true
	if click_on_145_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_145_26 = true
	if click_on_154_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_154_26 = true
	if key_on_130_29 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_130_29 = true
	if key_on_138_29 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_138_29 = true
	if click_on_145_29 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_145_29 = true
	if click_on_154_29 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_154_29 = true

func fn_fire(recoil: float = 0.2, shake: float = 0.05, impulse: float = 20.0) -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"32", "8822816724386196260")
	self.get_node("../Sfx/Fire").play()
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"34", "8822816724386196260")
	self.get_node("../Player/Roll/Cam/Gun/Flash").stop()
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"36", "8822816724386196260")
	self.get_node("../Player/Roll/Cam/Gun/Flash").play(&"pop")
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"39", "8822816724386196260")
	self.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"41", "8822816724386196260")
	self.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"SHOOT")
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"44", "8822816724386196260")
	self.ammo += -1
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"47", "8822816724386196260")
	self.get_node("../Player").set('recoil', recoil)
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"51", "8822816724386196260")
	var ray_51 = self.get_node("../Player/Roll/Cam/Aim")
	ray_51.force_raycast_update()
	if ray_51.is_colliding():
		var wire_51_collider = ray_51.get_collider()
		var wire_51_point = ray_51.get_collision_point()
		if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"53", "8822816724386196260")
		if (wire_51_collider).is_in_group(&"targets"):
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"56", "8822816724386196260")
			self.get_node("../Sfx/Hit").play()
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"58", "8822816724386196260")
			self.get_node("../Hud/Marker").stop()
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"60", "8822816724386196260")
			self.get_node("../Hud/Marker").play(&"hit")
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"63", "8822816724386196260")
			var spawned_63 = load('res://hit.tscn').instantiate()
			spawned_63.top_level = true
			spawned_63.position = (wire_51_point)
			self.get_parent().add_child.call_deferred(spawned_63)
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"66", "8822816724386196260")
			if tween_66 == null or not tween_66.is_running():
				var cam_66 = self.get_node("../Player/Roll/Cam")
				var shake_66 = self.create_tween()
				var jitter_h_66 = func(v: float) -> void: cam_66.h_offset = randf_range(-v, v)
				var jitter_v_66 = func(v: float) -> void: cam_66.v_offset = randf_range(-v, v)
				shake_66.tween_method(jitter_h_66, shake, 0.0, 0.2)
				shake_66.parallel().tween_method(jitter_v_66, shake, 0.0, 0.2)
				if shake_66:
					tween_66 = shake_66
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"70", "8822816724386196260")
			(wire_51_collider).linear_velocity = (((-self.get_node("../Player/Roll/Cam").global_transform.basis.z).normalized()) * impulse)
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"78", "8822816724386196260")
			self.score += 1
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"81", "8822816724386196260")
			self.get_node("../Hud/Score").text = ('Score: {0}').format([self.score, "", "", ""])
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"88", "8822816724386196260")
			self.hit_ball = (wire_51_collider)
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"91", "8822816724386196260")
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("fire", "go_to_Knocked", "8822816724386196260")
			var __hg_91_to = self.hit_ball
			if is_instance_valid(__hg_91_to) and "_STATE_CONTROLLER" in __hg_91_to:
				__hg_91_to._STATE_CONTROLLER.change_state("knocked")
		else:
			if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"92", "8822816724386196260")
			var spawned_92 = load('res://dust.tscn').instantiate()
			spawned_92.top_level = true
			spawned_92.position = (wire_51_point)
			self.get_parent().add_child.call_deferred(spawned_92)
	else:
		pass

func fn_fire_teardown() -> void:
	if tween_66 and tween_66.is_valid():
		for con_66: Dictionary in tween_66.finished.get_connections():
			tween_66.finished.disconnect(con_66.callable)
		tween_66.custom_step(9999.0)
		tween_66.kill()

func fn_show_ammo(label: String = '') -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"95", "8822816724386196260")
	self.get_node("../Hud/Ammo").text = ('{0}   {1} / {2}').format([label, self.ammo, self.mag, ""])

class Armed extends HengoState:
	class Semi extends HengoState:
		class Ready extends HengoState:
			func enter() -> void:
				_ref.click_on_203_23 = true
				_ref.clicked_203_23 = false
				_ref.key_on_130_23 = true
				_ref.key_hit_130_23 = false
				_ref.key_on_138_23 = true
				_ref.key_hit_138_23 = false
				_ref.click_on_145_23 = true
				_ref.clicked_145_23 = false
				_ref.click_on_154_23 = true
				_ref.clicked_154_23 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"102", "8822816724386196260")
				_ref.mag = _ref._mc_23_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"105", "8822816724386196260")
				_ref.ammo = _ref._mc_23_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"108", "8822816724386196260")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"115", "8822816724386196260")
				_ref.fn_show_ammo(_ref._mc_23_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"117", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"119", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"122", "8822816724386196260")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"129", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"203", "8822816724386196260")
					if _ref.clicked_203_23:
						_ref.clicked_203_23 = false
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"206", "8822816724386196260")
						_ref.fn_fire(0.06, 0.018, 22.0)
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"130", "8822816724386196260")
				if _ref.key_hit_130_23:
					_ref.key_hit_130_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"133", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"135", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"138", "8822816724386196260")
				if _ref.key_hit_138_23:
					_ref.key_hit_138_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"141", "8822816724386196260")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"144", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"145", "8822816724386196260")
				if _ref.clicked_145_23:
					_ref.clicked_145_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"148", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"150", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"153", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "next", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("burst")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"154", "8822816724386196260")
				if _ref.clicked_154_23:
					_ref.clicked_154_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"157", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"159", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"162", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "prev", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("auto")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"163", "8822816724386196260")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"167", "8822816724386196260")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"170", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.click_on_203_23 = false
				_ref.fn_fire_teardown()
				_ref.key_on_130_23 = false
				_ref.key_on_138_23 = false
				_ref.click_on_145_23 = false
				_ref.click_on_154_23 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"171", "8822816724386196260")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_23_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"178", "8822816724386196260")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"182", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"184", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"187", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"189", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"192", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"194", "8822816724386196260")
					_ref.ammo = _ref._mc_23_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"197", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	class Burst extends HengoState:
		class Ready extends HengoState:
			var cooldown_220_26: float = 0.0
			func enter() -> void:
				_ref.click_on_210_26 = true
				_ref.clicked_210_26 = false
				cooldown_220_26 = 0.0
				_ref.key_on_130_26 = true
				_ref.key_hit_130_26 = false
				_ref.key_on_138_26 = true
				_ref.key_hit_138_26 = false
				_ref.click_on_145_26 = true
				_ref.clicked_145_26 = false
				_ref.click_on_154_26 = true
				_ref.clicked_154_26 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"102", "8822816724386196260")
				_ref.mag = _ref._mc_26_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"105", "8822816724386196260")
				_ref.ammo = _ref._mc_26_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"108", "8822816724386196260")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"115", "8822816724386196260")
				_ref.fn_show_ammo(_ref._mc_26_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"117", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"119", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"122", "8822816724386196260")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"129", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"210", "8822816724386196260")
					if _ref.clicked_210_26:
						_ref.clicked_210_26 = false
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"213", "8822816724386196260")
						_ref.burst_left = 3
					else:
						pass
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"216", "8822816724386196260")
					if _ref.burst_left > 0:
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"220", "8822816724386196260")
						cooldown_220_26 = maxf(cooldown_220_26 - delta, 0.0)
						if cooldown_220_26 <= 0.0:
							cooldown_220_26 = 0.07
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"222", "8822816724386196260")
							_ref.fn_fire(0.045, 0.013, 16.0)
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"226", "8822816724386196260")
							_ref.burst_left += -1
						else:
							pass
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"130", "8822816724386196260")
				if _ref.key_hit_130_26:
					_ref.key_hit_130_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"133", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"135", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"138", "8822816724386196260")
				if _ref.key_hit_138_26:
					_ref.key_hit_138_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"141", "8822816724386196260")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"144", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"145", "8822816724386196260")
				if _ref.clicked_145_26:
					_ref.clicked_145_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"148", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"150", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"153", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "next", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("auto")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"154", "8822816724386196260")
				if _ref.clicked_154_26:
					_ref.clicked_154_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"157", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"159", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"162", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "prev", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("semi")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"163", "8822816724386196260")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"167", "8822816724386196260")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"170", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.click_on_210_26 = false
				_ref.fn_fire_teardown()
				_ref.key_on_130_26 = false
				_ref.key_on_138_26 = false
				_ref.click_on_145_26 = false
				_ref.click_on_154_26 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"171", "8822816724386196260")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_26_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"178", "8822816724386196260")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"182", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"184", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"187", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"189", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"192", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"194", "8822816724386196260")
					_ref.ammo = _ref._mc_26_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"197", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	class Auto extends HengoState:
		class Ready extends HengoState:
			var cooldown_232_29: float = 0.0
			func enter() -> void:
				cooldown_232_29 = 0.0
				_ref.key_on_130_29 = true
				_ref.key_hit_130_29 = false
				_ref.key_on_138_29 = true
				_ref.key_hit_138_29 = false
				_ref.click_on_145_29 = true
				_ref.clicked_145_29 = false
				_ref.click_on_154_29 = true
				_ref.clicked_154_29 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"102", "8822816724386196260")
				_ref.mag = _ref._mc_29_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"105", "8822816724386196260")
				_ref.ammo = _ref._mc_29_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"108", "8822816724386196260")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"115", "8822816724386196260")
				_ref.fn_show_ammo(_ref._mc_29_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"117", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"119", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"122", "8822816724386196260")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"129", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"229", "8822816724386196260")
					if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"232", "8822816724386196260")
						cooldown_232_29 = maxf(cooldown_232_29 - delta, 0.0)
						if cooldown_232_29 <= 0.0:
							cooldown_232_29 = 0.08
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"234", "8822816724386196260")
							_ref.fn_fire(0.035, 0.01, 13.0)
						else:
							pass
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"130", "8822816724386196260")
				if _ref.key_hit_130_29:
					_ref.key_hit_130_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"133", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"135", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"138", "8822816724386196260")
				if _ref.key_hit_138_29:
					_ref.key_hit_138_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"141", "8822816724386196260")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"144", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"145", "8822816724386196260")
				if _ref.clicked_145_29:
					_ref.clicked_145_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"148", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"150", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"153", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "next", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("semi")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"154", "8822816724386196260")
				if _ref.clicked_154_29:
					_ref.clicked_154_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"157", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"159", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"162", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "prev", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("burst")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"163", "8822816724386196260")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"167", "8822816724386196260")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"170", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.fn_fire_teardown()
				_ref.key_on_130_29 = false
				_ref.key_on_138_29 = false
				_ref.click_on_145_29 = false
				_ref.click_on_154_29 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"171", "8822816724386196260")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_29_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"178", "8822816724386196260")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"182", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"184", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"187", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"189", "8822816724386196260")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"192", "8822816724386196260")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"194", "8822816724386196260")
					_ref.ammo = _ref._mc_29_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"197", "8822816724386196260")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "8822816724386196260")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"198", "8822816724386196260")
		_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8822816724386196260", -1): HengoDebugger.trace_action(&"200", "8822816724386196260")
		_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
		change_sub_state("semi")

	func _init(_p) -> void:
		super(_p)
		add_sub_state("semi", Semi.new(_p))
		add_sub_state("burst", Burst.new(_p))
		add_sub_state("auto", Auto.new(_p))
