# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node3D

const HENGO_DEBUG_SCRIPT_ID = &'93255439189418083'

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		burst=Burst.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("burst")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class Burst extends HengoState:
	var window_3: float = 0.0
	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("93255439189418083", -1): HengoDebugger.trace_action(&"3", "93255439189418083")
		window_3 += delta
		if window_3 < 0.8:
			pass
		else:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("93255439189418083", -1): HengoDebugger.trace_action(&"5", "93255439189418083")
			_ref.queue_free()

	func enter() -> void:
		window_3 = 0.0
