# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends CharacterBody3D

const HENGO_DEBUG_SCRIPT_ID = &'7694910496626786900'

var speed = 6.0  
var sprint_speed = 10.5  
var air_speed = 4.5  
var dash_speed = 24.0  
var tilt = -1.0  
var roll_z = 0.0  
var sway_x = 0.0  
var recoil = 0.0  
var gun_home = -0.58135223  
var bob_power = 0.022  
var paused = false  
var gun_bob = 0.0  
var gun_bob_gain = 0.01  
var gun_bob_rate = 0.95  
 
var look_on_29: bool = false
var look_move_29: Vector2 = Vector2.ZERO
var key_on_143: bool = false
var key_hit_143: bool = false
var press_at_149: float = -99.0
var key_on_281: bool = false
var key_hit_281: bool = false

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		playing=Playing.new(self),
		paused=Paused.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("playing")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func _input(event: InputEvent) -> void:
	if look_on_29 and event is InputEventMouseMotion:
		look_move_29 += event.relative
	if key_on_143 and event is InputEventKey and event.keycode == KEY_ESCAPE and not event.echo:
		if event.pressed:
			key_hit_143 = true
	if event.is_action_pressed(&"ui_accept"):
		press_at_149 = Time.get_ticks_msec() / 1000.0
	if key_on_281 and event is InputEventKey and event.keycode == KEY_ESCAPE and not event.echo:
		if event.pressed:
			key_hit_281 = true

class Playing extends HengoState:
	var spring_vel_33: float = 0.0

	var spring_vel_78: float = 0.0

	var spring_vel_90: float = 0.0

	var spring_vel_95: float = 0.0

	var eight_phase_112: float = 0.0
	class Grounded extends HengoState:
		class Walking extends HengoState:
			var interval_186: float = 0.0
			func enter() -> void:
				interval_186 = 0.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"155", "7694910496626786900")
				_ref.gun_bob_gain = 0.01
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"158", "7694910496626786900")
				_ref.gun_bob_rate = 0.95

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"161", "7694910496626786900")
				var dir_161: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_161: Vector3 = (_ref.transform.basis * Vector3(dir_161.x, 0, dir_161.y)).normalized()
				_ref.velocity.x = world_161.x * _ref.speed
				_ref.velocity.z = world_161.z * _ref.speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"170", "7694910496626786900")
				if Input.is_key_pressed(KEY_SHIFT):
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"173", "7694910496626786900")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Walking", "go_to_Sprinting", "7694910496626786900")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("sprinting")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"174", "7694910496626786900")
				if ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"186", "7694910496626786900")
					interval_186 += delta
					if interval_186 >= 0.53:
						interval_186 = 0.0
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"188", "7694910496626786900")
						_ref.get_node("../Sfx/Step").play()
					else:
						pass
				else:
					pass

		class Sprinting extends HengoState:
			var interval_221: float = 0.0
			func enter() -> void:
				interval_221 = 0.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"190", "7694910496626786900")
				_ref.gun_bob_gain = 0.034
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"193", "7694910496626786900")
				_ref.gun_bob_rate = 1.5

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"196", "7694910496626786900")
				var dir_196: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_196: Vector3 = (_ref.transform.basis * Vector3(dir_196.x, 0, dir_196.y)).normalized()
				_ref.velocity.x = world_196.x * _ref.sprint_speed
				_ref.velocity.z = world_196.z * _ref.sprint_speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"205", "7694910496626786900")
				if Input.is_key_pressed(KEY_SHIFT):
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"208", "7694910496626786900")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Sprinting", "go_to_Walking", "7694910496626786900")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("walking")
					return
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"209", "7694910496626786900")
				if ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"221", "7694910496626786900")
					interval_221 += delta
					if interval_221 >= 0.33:
						interval_221 = 0.0
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"223", "7694910496626786900")
						_ref.get_node("../Sfx/Step").play()
					else:
						pass
				else:
					pass

		func physics(delta) -> void:
			super(delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"146", "7694910496626786900")
			if _ref.is_on_floor():
				pass
			else:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"148", "7694910496626786900")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Grounded", "go_to_Airborne", "7694910496626786900")
				_ref._STATE_CONTROLLER.current_state.change_sub_state("airborne")
				return
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"149", "7694910496626786900")
			if Time.get_ticks_msec() / 1000.0 - _ref.press_at_149 <= 0.2:
				_ref.press_at_149 = -99.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"152", "7694910496626786900")
				if _ref.is_on_floor():
					_ref.velocity.y = 8.0
			else:
				pass

		func _init(_p) -> void:
			super(_p)
			add_sub_state("walking", Walking.new(_p))
			add_sub_state("sprinting", Sprinting.new(_p))

		func enter() -> void:
			change_sub_state("walking")

	class Airborne extends HengoState:
		class Falling extends HengoState:
			var tap_at_240: float = -99.0
			var tap_down_240: bool = false
			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"231", "7694910496626786900")
				var dir_231: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_231: Vector3 = (_ref.transform.basis * Vector3(dir_231.x, 0, dir_231.y)).normalized()
				_ref.velocity.x = world_231.x * _ref.air_speed
				_ref.velocity.z = world_231.z * _ref.air_speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"240", "7694910496626786900")
				var down_240: bool = Input.is_key_pressed(KEY_SHIFT)
				var pressed_240: bool = down_240 and not tap_down_240
				var paired_240: bool = false
				tap_down_240 = down_240
				if pressed_240:
					var now_240: float = Time.get_ticks_msec() / 1000.0
					paired_240 = now_240 - tap_at_240 <= 0.3
					tap_at_240 = -99.0 if paired_240 else now_240
				if paired_240:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"243", "7694910496626786900")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Falling", "go_to_Dashing", "7694910496626786900")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("dashing")
					return
				else:
					pass

			func enter() -> void:
				tap_at_240 = -99.0
				tap_down_240 = false

		class Dashing extends HengoState:
			var did_244: bool = false

			var window_273: float = 0.0
			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"244", "7694910496626786900")
				if not did_244:
					did_244 = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"245", "7694910496626786900")
					var dir_245: Vector2 = ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")) if (((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1) else (Vector2(0.0, -1.0)))
					var world_245: Vector3 = (_ref.transform.basis * Vector3(dir_245.x, 0, dir_245.y)).normalized()
					_ref.velocity.x = world_245.x * _ref.dash_speed
					_ref.velocity.z = world_245.z * _ref.dash_speed
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"273", "7694910496626786900")
				window_273 += delta
				if window_273 < 0.18:
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"275", "7694910496626786900")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Dashing", "go_to_Falling", "7694910496626786900")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("falling")
					return

			func enter() -> void:
				did_244 = false
				window_273 = 0.0

		func enter() -> void:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"225", "7694910496626786900")
			_ref.gun_bob_gain = 0.0
			change_sub_state("falling")

		func physics(delta) -> void:
			super(delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"228", "7694910496626786900")
			if _ref.is_on_floor():
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"230", "7694910496626786900")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Airborne", "go_to_Grounded", "7694910496626786900")
				_ref._STATE_CONTROLLER.current_state.change_sub_state("grounded")
				return
			else:
				pass

		func _init(_p) -> void:
			super(_p)
			add_sub_state("falling", Falling.new(_p))
			add_sub_state("dashing", Dashing.new(_p))

	func enter() -> void:
		_ref.look_on_29 = true
		_ref.look_move_29 = Vector2.ZERO
		spring_vel_33 = 0.0
		spring_vel_78 = 0.0
		spring_vel_90 = 0.0
		spring_vel_95 = 0.0
		_ref.key_on_143 = true
		_ref.key_hit_143 = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"24", "7694910496626786900")
		_ref.paused = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"27", "7694910496626786900")
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
		change_sub_state("grounded")

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"29", "7694910496626786900")
		var cam_29 = _ref.get_node("Roll/Cam")
		var pitch_29: float = deg_to_rad(85.0)
		_ref.rotate_y(-_ref.look_move_29.x * 0.0025)
		cam_29.rotation.x = clamp(cam_29.rotation.x - _ref.look_move_29.y * 0.0025, -pitch_29, pitch_29)
		_ref.look_move_29 = Vector2.ZERO
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"33", "7694910496626786900")
		spring_vel_33 += ((((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).x) * _ref.tilt) - _ref.roll_z) * 90.0 * delta
		spring_vel_33 *= clampf(1.0 - 14.0 * delta, 0.0, 1.0)
		_ref.roll_z += spring_vel_33 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"49", "7694910496626786900")
		_ref.get_node("Roll").rotation_degrees = (Vector3(0.0, 0.0, _ref.roll_z))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"56", "7694910496626786900")
		_ref.get_node("Roll").position = (Vector3(0.0, ((sin(Time.get_ticks_msec() / 1000.0 * 1.9 * TAU) * _ref.bob_power) * ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length())), 0.0))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"78", "7694910496626786900")
		spring_vel_78 += ((((Input.get_last_mouse_velocity()).x) * -1.8e-05) - _ref.sway_x) * 70.0 * delta
		spring_vel_78 *= clampf(1.0 - 13.0 * delta, 0.0, 1.0)
		_ref.sway_x += spring_vel_78 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"90", "7694910496626786900")
		spring_vel_90 += (0.0 - _ref.recoil) * 220.0 * delta
		spring_vel_90 *= clampf(1.0 - 22.0 * delta, 0.0, 1.0)
		_ref.recoil += spring_vel_90 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"95", "7694910496626786900")
		spring_vel_95 += ((_ref.gun_bob_gain * ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length())) - _ref.gun_bob) * 40.0 * delta
		spring_vel_95 *= clampf(1.0 - 9.0 * delta, 0.0, 1.0)
		_ref.gun_bob += spring_vel_95 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"112", "7694910496626786900")
		eight_phase_112 = fmod(eight_phase_112 + _ref.gun_bob_rate * delta, 1.0)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"115", "7694910496626786900")
		_ref.get_node("Roll/Cam/Gun").position = (Vector3(((0.31350517 + _ref.sway_x) + (sin(eight_phase_112 * TAU) * _ref.gun_bob)), (-0.22229338 + (sin(eight_phase_112 * TAU * 2.0) * _ref.gun_bob * 0.5)), (_ref.gun_home + _ref.recoil)))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"138", "7694910496626786900")
		_ref.velocity.y -= 24.0 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"141", "7694910496626786900")
		_ref.move_and_slide()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"143", "7694910496626786900")
		if _ref.key_hit_143:
			_ref.key_hit_143 = false
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Playing", "go_to_Paused", "7694910496626786900")
			_ref._STATE_CONTROLLER.change_state("paused")
			return
		else:
			pass

	func exit() -> void:
		super()
		_ref.look_on_29 = false
		_ref.key_on_143 = false

	func _init(_p) -> void:
		super(_p)
		add_sub_state("grounded", Grounded.new(_p))
		add_sub_state("airborne", Airborne.new(_p))

class Paused extends HengoState:
	func enter() -> void:
		_ref.key_on_281 = true
		_ref.key_hit_281 = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"276", "7694910496626786900")
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"278", "7694910496626786900")
		_ref.paused = true

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_action(&"281", "7694910496626786900")
		if _ref.key_hit_281:
			_ref.key_hit_281 = false
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("7694910496626786900", -1): HengoDebugger.trace_state_transition("Paused", "go_to_Playing", "7694910496626786900")
			_ref._STATE_CONTROLLER.change_state("playing")
			return
		else:
			pass

	func exit() -> void:
		super()
		_ref.key_on_281 = false
