# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends RigidBody3D

const HENGO_DEBUG_SCRIPT_ID = &'2772648138587788778'

var home = Vector3(0, 0, 0)  
 
var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		standing=Standing.new(self),
		knocked=Knocked.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("standing")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class Standing extends HengoState:
	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"5", "2772648138587788778")
		_ref.home = (_ref.global_position)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"10", "2772648138587788778")
		var node_10 = _ref
		if node_10 is GeometryInstance3D:
			if (node_10 as GeometryInstance3D).material_override == null:
				(node_10 as GeometryInstance3D).material_override = StandardMaterial3D.new()
			var material_10 := (node_10 as GeometryInstance3D).material_override as StandardMaterial3D
			if material_10:
				material_10.albedo_color = Color(0.9, 0.35, 0.3, 1)

class Knocked extends HengoState:
	var tween_13: Tween = null

	var window_20: float = 0.0
	func enter() -> void:
		window_20 = 0.0
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"13", "2772648138587788778")
		var node_13 = _ref.get_node("Mesh")
		var flash_13: Tween = null
		if node_13 is GeometryInstance3D:
			if (node_13 as GeometryInstance3D).material_override == null:
				(node_13 as GeometryInstance3D).material_override = StandardMaterial3D.new()
			var material_13 := (node_13 as GeometryInstance3D).material_override as StandardMaterial3D
			if material_13:
				var orig_13 = material_13.albedo_color
				flash_13 = _ref.create_tween()
				flash_13.tween_property(material_13, "albedo_color", Color(1, 1, 1, 1), 0.18 * 0.5)
				flash_13.tween_property(material_13, "albedo_color", orig_13, 0.18 * 0.5)
		if flash_13:
			tween_13 = flash_13
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"17", "2772648138587788778")
		_ref.apply_torque_impulse(Vector3(0, 0, 6))

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"20", "2772648138587788778")
		window_20 += delta
		if window_20 < 2.0:
			pass
		else:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"22", "2772648138587788778")
			_ref.linear_velocity = Vector3.ZERO
			_ref.angular_velocity = Vector3.ZERO
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"24", "2772648138587788778")
			_ref.global_position = _ref.home
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"27", "2772648138587788778")
			_ref.rotation_degrees = Vector3(0, 0, 0)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_action(&"30", "2772648138587788778")
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("2772648138587788778", -1): HengoDebugger.trace_state_transition("Knocked", "go_to_Standing", "2772648138587788778")
			_ref._STATE_CONTROLLER.change_state("standing")
			return

	func exit() -> void:
		super()
		if tween_13 and tween_13.is_valid():
			for con_13: Dictionary in tween_13.finished.get_connections():
				tween_13.finished.disconnect(con_13.callable)
			tween_13.custom_step(9999.0)
			tween_13.kill()
