# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends CharacterBody3D

const HENGO_DEBUG_SCRIPT_ID = &'330811692581239653'

var health = 4  
var max_health = 4  
var speed = 3.5  
var chase_speed = 5.5  
 
var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		patrolling=Patrolling.new(self),
		chasing=Chasing.new(self),
		hit=Hit.new(self),
		dying=Dying.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("patrolling")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func fn_see_player(range: float = 12.0) -> StringName:
	if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"18", "330811692581239653")
	if (self.global_position.distance_to(self.get_node("../Player").global_position)) < range:
		if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"22", "330811692581239653")
		var target_22 = self.get_node("../Player")
		var skip_22: Array[RID] = [(self as CollisionObject3D).get_rid()]
		var query_22 = PhysicsRayQueryParameters3D.create(self.global_position, target_22.global_position)
		query_22.exclude = skip_22
		var hit_22 = self.get_world_3d().direct_space_state.intersect_ray(query_22)
		if hit_22.is_empty() or hit_22.collider == target_22:
			if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"26", "330811692581239653")
			return &'see_player_spotted'
		else:
			if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"28", "330811692581239653")
			return &'see_player_lost'
	else:
		if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"30", "330811692581239653")
		return &'see_player_lost'
	return &''

func fn_wander() -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"36", "330811692581239653")
	self.get_node("Agent").target_position = (((self.get_tree().get_nodes_in_group(&"spawns")).pick_random()).global_position)

class Patrolling extends HengoState:
	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"41", "330811692581239653")
		var node_41 = _ref.get_node("Mesh")
		if node_41 is GeometryInstance3D:
			if (node_41 as GeometryInstance3D).material_override == null:
				(node_41 as GeometryInstance3D).material_override = StandardMaterial3D.new()
			var material_41 := (node_41 as GeometryInstance3D).material_override as StandardMaterial3D
			if material_41:
				material_41.albedo_color = Color(0.45, 0.55, 0.7, 1)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"44", "330811692581239653")
		_ref.fn_wander()

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"45", "330811692581239653")
		_ref.velocity.y -= 24.0 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"48", "330811692581239653")
		var to_48 = _ref.get_node("Agent").get_next_path_position() - _ref.global_position
		var dir_48 = Vector3(to_48.x, 0.0, to_48.z).normalized()
		_ref.velocity = Vector3(dir_48.x * _ref.speed, _ref.velocity.y, dir_48.z * _ref.speed)
		_ref.move_and_slide()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"52", "330811692581239653")
		if _ref.get_node("Agent").is_navigation_finished():
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"54", "330811692581239653")
			_ref.fn_wander()
		else:
			pass
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"55", "330811692581239653")
		match _ref.fn_see_player(12.0):
			&'see_player_spotted':
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_state_transition("Patrolling", "go_to_Chasing", "330811692581239653")
				_ref._STATE_CONTROLLER.change_state("chasing")
				return
			&'see_player_lost':
				pass

class Chasing extends HengoState:
	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"57", "330811692581239653")
		var node_57 = _ref.get_node("Mesh")
		if node_57 is GeometryInstance3D:
			if (node_57 as GeometryInstance3D).material_override == null:
				(node_57 as GeometryInstance3D).material_override = StandardMaterial3D.new()
			var material_57 := (node_57 as GeometryInstance3D).material_override as StandardMaterial3D
			if material_57:
				material_57.albedo_color = Color(0.9, 0.3, 0.25, 1)

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"60", "330811692581239653")
		_ref.get_node("Agent").target_position = (_ref.get_node("../Player").global_position)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"65", "330811692581239653")
		_ref.velocity.y -= 24.0 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"68", "330811692581239653")
		var to_68 = _ref.get_node("Agent").get_next_path_position() - _ref.global_position
		var dir_68 = Vector3(to_68.x, 0.0, to_68.z).normalized()
		_ref.velocity = Vector3(dir_68.x * _ref.chase_speed, _ref.velocity.y, dir_68.z * _ref.chase_speed)
		_ref.move_and_slide()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"75", "330811692581239653")
		if (_ref.global_position.distance_to(_ref.get_node("../Player").global_position)) > 20:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_state_transition("Chasing", "go_to_Patrolling", "330811692581239653")
			_ref._STATE_CONTROLLER.change_state("patrolling")
			return
		else:
			pass

class Hit extends HengoState:
	var tween_79: Tween = null
	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"79", "330811692581239653")
		var node_79 = _ref.get_node("Mesh")
		var flash_79: Tween = null
		if node_79 is GeometryInstance3D:
			if (node_79 as GeometryInstance3D).material_override == null:
				(node_79 as GeometryInstance3D).material_override = StandardMaterial3D.new()
			var material_79 := (node_79 as GeometryInstance3D).material_override as StandardMaterial3D
			if material_79:
				var orig_79 = material_79.albedo_color
				flash_79 = _ref.create_tween()
				flash_79.tween_property(material_79, "albedo_color", Color(1, 1, 1, 1), 0.14 * 0.5)
				flash_79.tween_property(material_79, "albedo_color", orig_79, 0.14 * 0.5)
		if flash_79:
			tween_79 = flash_79

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"83", "330811692581239653")
		if _ref.health <= 0:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_state_transition("Hit", "go_to_Dying", "330811692581239653")
			_ref._STATE_CONTROLLER.change_state("dying")
			return
		else:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_state_transition("Hit", "go_to_Chasing", "330811692581239653")
			_ref._STATE_CONTROLLER.change_state("chasing")
			return

	func exit() -> void:
		super()
		if tween_79 and tween_79.is_valid():
			for con_79: Dictionary in tween_79.finished.get_connections():
				tween_79.finished.disconnect(con_79.callable)
			tween_79.custom_step(9999.0)
			tween_79.kill()

class Dying extends HengoState:
	var window_96: float = 0.0
	func enter() -> void:
		window_96 = 0.0
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"87", "330811692581239653")
		_ref.velocity = Vector3(0, 0, 0)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"90", "330811692581239653")
		_ref.visible = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"93", "330811692581239653")
		_ref.global_position = Vector3(0, -50, 0)

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"96", "330811692581239653")
		window_96 += delta
		if window_96 < 3.0:
			pass
		else:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"102", "330811692581239653")
			_ref.global_position = (((_ref.get_tree().get_nodes_in_group(&"spawns")).pick_random()).global_position)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"107", "330811692581239653")
			_ref.health = _ref.max_health
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"110", "330811692581239653")
			_ref.visible = true
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_action(&"113", "330811692581239653")
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("330811692581239653", -1): HengoDebugger.trace_state_transition("Dying", "go_to_Patrolling", "330811692581239653")
			_ref._STATE_CONTROLLER.change_state("patrolling")
			return
