# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node3D

const HENGO_DEBUG_SCRIPT_ID = &'6323274929898634019'

var ammo = 30  
var mag = 30  
var score = 0  
var hit_node = null  
var burst_left = 0  
var empty_reload = false  
 
var click_on_235_23: bool = false
var clicked_235_23: bool = false
var key_on_162_23: bool = false
var key_hit_162_23: bool = false
var key_on_170_23: bool = false
var key_hit_170_23: bool = false
var click_on_177_23: bool = false
var clicked_177_23: bool = false
var click_on_186_23: bool = false
var clicked_186_23: bool = false
var click_on_242_26: bool = false
var clicked_242_26: bool = false
var key_on_162_26: bool = false
var key_hit_162_26: bool = false
var key_on_170_26: bool = false
var key_hit_170_26: bool = false
var click_on_177_26: bool = false
var clicked_177_26: bool = false
var click_on_186_26: bool = false
var clicked_186_26: bool = false
var key_on_162_29: bool = false
var key_hit_162_29: bool = false
var key_on_170_29: bool = false
var key_hit_170_29: bool = false
var click_on_177_29: bool = false
var clicked_177_29: bool = false
var click_on_186_29: bool = false
var clicked_186_29: bool = false
var tween_66: Tween = null
var _mc_23_label = 'SEMI'
var _mc_23_rounds = 30
var _mc_26_label = 'BURST'
var _mc_26_rounds = 30
var _mc_29_label = 'AUTO'
var _mc_29_rounds = 30

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		armed=Armed.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("armed")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func _input(event: InputEvent) -> void:
	if click_on_235_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed and not event.double_click:
			clicked_235_23 = true
	if key_on_162_23 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_162_23 = true
	if key_on_170_23 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_170_23 = true
	if click_on_177_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_177_23 = true
	if click_on_186_23 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_186_23 = true
	if click_on_242_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed and not event.double_click:
			clicked_242_26 = true
	if key_on_162_26 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_162_26 = true
	if key_on_170_26 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_170_26 = true
	if click_on_177_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_177_26 = true
	if click_on_186_26 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_186_26 = true
	if key_on_162_29 and event is InputEventKey and event.keycode == KEY_F and not event.echo:
		if event.pressed:
			key_hit_162_29 = true
	if key_on_170_29 and event is InputEventKey and event.keycode == KEY_R and not event.echo:
		if event.pressed:
			key_hit_170_29 = true
	if click_on_177_29 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_UP:
		if event.pressed:
			clicked_177_29 = true
	if click_on_186_29 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
		if event.pressed:
			clicked_186_29 = true

func fn_fire(recoil: float = 0.2, shake: float = 0.05, impulse: float = 20.0) -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"32", "6323274929898634019")
	self.get_node("../Sfx/Fire").play()
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"34", "6323274929898634019")
	self.get_node("../Player/Roll/Cam/Gun/Flash").stop()
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"36", "6323274929898634019")
	self.get_node("../Player/Roll/Cam/Gun/Flash").play(&"pop")
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"39", "6323274929898634019")
	self.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"41", "6323274929898634019")
	self.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"SHOOT")
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"44", "6323274929898634019")
	self.ammo += -1
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"47", "6323274929898634019")
	self.get_node("../Player").set('recoil', recoil)
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"51", "6323274929898634019")
	var ray_51 = self.get_node("../Player/Roll/Cam/Aim")
	ray_51.force_raycast_update()
	if ray_51.is_colliding():
		var wire_51_collider = ray_51.get_collider()
		var wire_51_point = ray_51.get_collision_point()
		if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"53", "6323274929898634019")
		if (wire_51_collider).is_in_group(&"targets"):
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"56", "6323274929898634019")
			self.get_node("../Sfx/Hit").play()
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"58", "6323274929898634019")
			self.get_node("../Hud/Marker").stop()
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"60", "6323274929898634019")
			self.get_node("../Hud/Marker").play(&"hit")
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"63", "6323274929898634019")
			var spawned_63 = load('res://hit.tscn').instantiate()
			spawned_63.top_level = true
			spawned_63.position = (wire_51_point)
			self.get_parent().add_child.call_deferred(spawned_63)
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"66", "6323274929898634019")
			if tween_66 == null or not tween_66.is_running():
				var cam_66 = self.get_node("../Player/Roll/Cam")
				var shake_66 = self.create_tween()
				var jitter_h_66 = func(v: float) -> void: cam_66.h_offset = randf_range(-v, v)
				var jitter_v_66 = func(v: float) -> void: cam_66.v_offset = randf_range(-v, v)
				shake_66.tween_method(jitter_h_66, shake, 0.0, 0.2)
				shake_66.parallel().tween_method(jitter_v_66, shake, 0.0, 0.2)
				if shake_66:
					tween_66 = shake_66
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"70", "6323274929898634019")
			(wire_51_collider).linear_velocity = (((-self.get_node("../Player/Roll/Cam").global_transform.basis.z).normalized()) * impulse)
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"78", "6323274929898634019")
			self.hit_node = (wire_51_collider)
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"81", "6323274929898634019")
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("fire", "go_to_Knocked", "6323274929898634019")
			var __hg_81_to = self.hit_node
			if is_instance_valid(__hg_81_to) and "_STATE_CONTROLLER" in __hg_81_to:
				__hg_81_to._STATE_CONTROLLER.change_state("knocked")
		else:
			if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"82", "6323274929898634019")
			if (wire_51_collider).is_in_group(&"guards"):
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"85", "6323274929898634019")
				self.get_node("../Sfx/Hit").play()
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"87", "6323274929898634019")
				self.get_node("../Hud/Marker").stop()
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"89", "6323274929898634019")
				self.get_node("../Hud/Marker").play(&"hit")
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"92", "6323274929898634019")
				self.hit_node = (wire_51_collider)
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"95", "6323274929898634019")
				self.hit_node.set('health', ((self.hit_node.get_indexed('health')) - 1))
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"106", "6323274929898634019")
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("fire", "go_to_Hit", "6323274929898634019")
				var __hg_106_to = self.hit_node
				if is_instance_valid(__hg_106_to) and "_STATE_CONTROLLER" in __hg_106_to:
					__hg_106_to._STATE_CONTROLLER.change_state("hit")
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"107", "6323274929898634019")
				if (self.hit_node.get_indexed('health')) <= 0:
					if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"114", "6323274929898634019")
					self.score += 1
					if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"117", "6323274929898634019")
					self.get_node("../Hud/Score").text = ('Guards down: {0}').format([self.score, "", "", ""])
				else:
					pass
			else:
				if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"124", "6323274929898634019")
				var spawned_124 = load('res://dust.tscn').instantiate()
				spawned_124.top_level = true
				spawned_124.position = (wire_51_point)
				self.get_parent().add_child.call_deferred(spawned_124)
	else:
		pass

func fn_fire_teardown() -> void:
	if tween_66 and tween_66.is_valid():
		for con_66: Dictionary in tween_66.finished.get_connections():
			tween_66.finished.disconnect(con_66.callable)
		tween_66.custom_step(9999.0)
		tween_66.kill()

func fn_show_ammo(label: String = '') -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"127", "6323274929898634019")
	self.get_node("../Hud/Ammo").text = ('{0}   {1} / {2}').format([label, self.ammo, self.mag, ""])

class Armed extends HengoState:
	class Semi extends HengoState:
		class Ready extends HengoState:
			func enter() -> void:
				_ref.click_on_235_23 = true
				_ref.clicked_235_23 = false
				_ref.key_on_162_23 = true
				_ref.key_hit_162_23 = false
				_ref.key_on_170_23 = true
				_ref.key_hit_170_23 = false
				_ref.click_on_177_23 = true
				_ref.clicked_177_23 = false
				_ref.click_on_186_23 = true
				_ref.clicked_186_23 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"134", "6323274929898634019")
				_ref.mag = _ref._mc_23_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"137", "6323274929898634019")
				_ref.ammo = _ref._mc_23_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"140", "6323274929898634019")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"147", "6323274929898634019")
				_ref.fn_show_ammo(_ref._mc_23_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"149", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"151", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"154", "6323274929898634019")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"161", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"235", "6323274929898634019")
					if _ref.clicked_235_23:
						_ref.clicked_235_23 = false
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"238", "6323274929898634019")
						_ref.fn_fire(0.06, 0.018, 22.0)
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"162", "6323274929898634019")
				if _ref.key_hit_162_23:
					_ref.key_hit_162_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"165", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"167", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"170", "6323274929898634019")
				if _ref.key_hit_170_23:
					_ref.key_hit_170_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"173", "6323274929898634019")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"176", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"177", "6323274929898634019")
				if _ref.clicked_177_23:
					_ref.clicked_177_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"180", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"182", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"185", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "next", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("burst")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"186", "6323274929898634019")
				if _ref.clicked_186_23:
					_ref.clicked_186_23 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"189", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"191", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"194", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "prev", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("auto")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"195", "6323274929898634019")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"199", "6323274929898634019")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"202", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.click_on_235_23 = false
				_ref.fn_fire_teardown()
				_ref.key_on_162_23 = false
				_ref.key_on_170_23 = false
				_ref.click_on_177_23 = false
				_ref.click_on_186_23 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"203", "6323274929898634019")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_23_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"210", "6323274929898634019")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"214", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"216", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"219", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"221", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"224", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"226", "6323274929898634019")
					_ref.ammo = _ref._mc_23_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"229", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	class Burst extends HengoState:
		class Ready extends HengoState:
			var cooldown_252_26: float = 0.0
			func enter() -> void:
				_ref.click_on_242_26 = true
				_ref.clicked_242_26 = false
				cooldown_252_26 = 0.0
				_ref.key_on_162_26 = true
				_ref.key_hit_162_26 = false
				_ref.key_on_170_26 = true
				_ref.key_hit_170_26 = false
				_ref.click_on_177_26 = true
				_ref.clicked_177_26 = false
				_ref.click_on_186_26 = true
				_ref.clicked_186_26 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"134", "6323274929898634019")
				_ref.mag = _ref._mc_26_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"137", "6323274929898634019")
				_ref.ammo = _ref._mc_26_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"140", "6323274929898634019")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"147", "6323274929898634019")
				_ref.fn_show_ammo(_ref._mc_26_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"149", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"151", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"154", "6323274929898634019")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"161", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"242", "6323274929898634019")
					if _ref.clicked_242_26:
						_ref.clicked_242_26 = false
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"245", "6323274929898634019")
						_ref.burst_left = 3
					else:
						pass
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"248", "6323274929898634019")
					if _ref.burst_left > 0:
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"252", "6323274929898634019")
						cooldown_252_26 = maxf(cooldown_252_26 - delta, 0.0)
						if cooldown_252_26 <= 0.0:
							cooldown_252_26 = 0.07
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"254", "6323274929898634019")
							_ref.fn_fire(0.045, 0.013, 16.0)
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"258", "6323274929898634019")
							_ref.burst_left += -1
						else:
							pass
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"162", "6323274929898634019")
				if _ref.key_hit_162_26:
					_ref.key_hit_162_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"165", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"167", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"170", "6323274929898634019")
				if _ref.key_hit_170_26:
					_ref.key_hit_170_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"173", "6323274929898634019")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"176", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"177", "6323274929898634019")
				if _ref.clicked_177_26:
					_ref.clicked_177_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"180", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"182", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"185", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "next", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("auto")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"186", "6323274929898634019")
				if _ref.clicked_186_26:
					_ref.clicked_186_26 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"189", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"191", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"194", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "prev", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("semi")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"195", "6323274929898634019")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"199", "6323274929898634019")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"202", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.click_on_242_26 = false
				_ref.fn_fire_teardown()
				_ref.key_on_162_26 = false
				_ref.key_on_170_26 = false
				_ref.click_on_177_26 = false
				_ref.click_on_186_26 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"203", "6323274929898634019")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_26_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"210", "6323274929898634019")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"214", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"216", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"219", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"221", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"224", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"226", "6323274929898634019")
					_ref.ammo = _ref._mc_26_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"229", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	class Auto extends HengoState:
		class Ready extends HengoState:
			var cooldown_264_29: float = 0.0
			func enter() -> void:
				cooldown_264_29 = 0.0
				_ref.key_on_162_29 = true
				_ref.key_hit_162_29 = false
				_ref.key_on_170_29 = true
				_ref.key_hit_170_29 = false
				_ref.click_on_177_29 = true
				_ref.clicked_177_29 = false
				_ref.click_on_186_29 = true
				_ref.clicked_186_29 = false
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"134", "6323274929898634019")
				_ref.mag = _ref._mc_29_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"137", "6323274929898634019")
				_ref.ammo = _ref._mc_29_rounds
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"140", "6323274929898634019")
				_ref.burst_left = 0

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"147", "6323274929898634019")
				_ref.fn_show_ammo(_ref._mc_29_label)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"149", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"151", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"IDLE")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"154", "6323274929898634019")
				if (_ref.get_node("../Player").get_indexed('paused')) == false:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"161", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"261", "6323274929898634019")
					if Input.is_mouse_button_pressed(MOUSE_BUTTON_LEFT):
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"264", "6323274929898634019")
						cooldown_264_29 = maxf(cooldown_264_29 - delta, 0.0)
						if cooldown_264_29 <= 0.0:
							cooldown_264_29 = 0.08
							if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"266", "6323274929898634019")
							_ref.fn_fire(0.035, 0.01, 13.0)
						else:
							pass
					else:
						pass
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"162", "6323274929898634019")
				if _ref.key_hit_162_29:
					_ref.key_hit_162_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"165", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"167", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"INSPEC")
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"170", "6323274929898634019")
				if _ref.key_hit_170_29:
					_ref.key_hit_170_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"173", "6323274929898634019")
					_ref.empty_reload = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"176", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"177", "6323274929898634019")
				if _ref.clicked_177_29:
					_ref.clicked_177_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"180", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"182", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"185", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "next", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("semi")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"186", "6323274929898634019")
				if _ref.clicked_186_29:
					_ref.clicked_186_29 = false
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"189", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"191", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"194", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "prev", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.change_sub_state("burst")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"195", "6323274929898634019")
				if _ref.ammo <= 0:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"199", "6323274929898634019")
					_ref.empty_reload = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"202", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Ready", "go_to_Reloading", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("reloading")
					return
				else:
					pass

			func exit() -> void:
				super()
				_ref.fn_fire_teardown()
				_ref.key_on_162_29 = false
				_ref.key_on_170_29 = false
				_ref.click_on_177_29 = false
				_ref.click_on_186_29 = false

		class Reloading extends HengoState:
			func enter() -> void:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"203", "6323274929898634019")
				_ref.get_node("../Hud/Ammo").text = ('{0}   RELOADING').format([_ref._mc_29_label, "", "", ""])
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"210", "6323274929898634019")
				if _ref.empty_reload == true:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"214", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"216", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD2")
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"219", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"221", "6323274929898634019")
					_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"RELOAD1")

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"224", "6323274929898634019")
				if _ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").is_playing():
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"226", "6323274929898634019")
					_ref.ammo = _ref._mc_29_rounds
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"229", "6323274929898634019")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_state_transition("Reloading", "go_to_Ready", "6323274929898634019")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("ready")
					return

		func _init(_p) -> void:
			super(_p)
			add_sub_state("ready", Ready.new(_p))
			add_sub_state("reloading", Reloading.new(_p))

		func enter() -> void:
			change_sub_state("ready")

	func enter() -> void:
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"230", "6323274929898634019")
		_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").stop()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("6323274929898634019", -1): HengoDebugger.trace_action(&"232", "6323274929898634019")
		_ref.get_node("../Player/Roll/Cam/Gun/View/AnimationPlayer").play(&"DRAW")
		change_sub_state("semi")

	func _init(_p) -> void:
		super(_p)
		add_sub_state("semi", Semi.new(_p))
		add_sub_state("burst", Burst.new(_p))
		add_sub_state("auto", Auto.new(_p))
