# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Control

const HENGO_DEBUG_SCRIPT_ID = &'3837606583069712313'

var sense = 0.0025  
var lit = true  
var world_env = null  
var no_env = null  
 
var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		open=Open.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("open")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func fn_show_sense() -> void:
	if self.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"8", "3837606583069712313")
	self.get_node("Frame/Box/SenseRow/Amount").text = ('{0}').format([self.sense, "", "", ""])

class Open extends HengoState:
	var emitter_22 = null
	var fired_22: bool = false
	var value_22 = null

	func _on_signal_22(arg_22) -> void:
		value_22 = arg_22
		fired_22 = true

	var emitter_30 = null
	var fired_30: bool = false
	var value_30 = null

	func _on_signal_30(arg_30) -> void:
		value_30 = arg_30
		fired_30 = true
	func enter() -> void:
		fired_22 = false
		emitter_22 = _ref.get_node("Frame/Box/SenseRow/Sense")
		if is_instance_valid(emitter_22) and not emitter_22.is_connected('value_changed', _on_signal_22):
			emitter_22.connect('value_changed', _on_signal_22)
		fired_30 = false
		emitter_30 = _ref.get_node("Frame/Box/Env")
		if is_instance_valid(emitter_30) and not emitter_30.is_connected('toggled', _on_signal_30):
			emitter_30.connect('toggled', _on_signal_30)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"15", "3837606583069712313")
		_ref.world_env = (_ref.get_node("../../World").get_indexed('environment'))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"21", "3837606583069712313")
		_ref.fn_show_sense()

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"22", "3837606583069712313")
		if fired_22:
			fired_22 = false
			_ref.sense = value_22
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"25", "3837606583069712313")
			_ref.get_node("../../Player").set('look_sense', _ref.sense)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"29", "3837606583069712313")
			_ref.fn_show_sense()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"30", "3837606583069712313")
		if fired_30:
			fired_30 = false
			_ref.lit = value_30
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"33", "3837606583069712313")
			if _ref.lit == true:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"37", "3837606583069712313")
				_ref.get_node("../../World").set('environment', _ref.world_env)
			else:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("3837606583069712313", -1): HengoDebugger.trace_action(&"41", "3837606583069712313")
				_ref.get_node("../../World").set('environment', _ref.no_env)

	func exit() -> void:
		super()
		if is_instance_valid(emitter_22) and emitter_22.is_connected('value_changed', _on_signal_22):
			emitter_22.disconnect('value_changed', _on_signal_22)
		if is_instance_valid(emitter_30) and emitter_30.is_connected('toggled', _on_signal_30):
			emitter_30.disconnect('toggled', _on_signal_30)
