# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends CharacterBody3D

const HENGO_DEBUG_SCRIPT_ID = &'8613291214389966227'

var speed = 6.0  
var sprint_speed = 10.5  
var air_speed = 4.5  
var dash_speed = 24.0  
var tilt = -1.0  
var roll_z = 0.0  
var sway_x = 0.0  
var recoil = 0.0  
var gun_home = -0.58135223  
var bob_power = 0.022  
var paused = false  
var gun_bob = 0.0  
var gun_bob_gain = 0.01  
var gun_bob_rate = 0.95  
var ground_speed = 6.0  
var aim = 0.0  
var look_sense = 0.0025  
 
var look_on_35: bool = false
var look_move_35: Vector2 = Vector2.ZERO
var key_on_191: bool = false
var key_hit_191: bool = false
var press_at_197: float = -99.0
var key_on_345: bool = false
var key_hit_345: bool = false

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		playing=Playing.new(self),
		paused=Paused.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("playing")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func _input(event: InputEvent) -> void:
	if look_on_35 and event is InputEventMouseMotion:
		look_move_35 += event.relative
	if key_on_191 and event is InputEventKey and event.keycode == KEY_ESCAPE and not event.echo:
		if event.pressed:
			key_hit_191 = true
	if event.is_action_pressed(&"ui_accept"):
		press_at_197 = Time.get_ticks_msec() / 1000.0
	if key_on_345 and event is InputEventKey and event.keycode == KEY_ESCAPE and not event.echo:
		if event.pressed:
			key_hit_345 = true

class Playing extends HengoState:
	var spring_vel_39: float = 0.0

	var spring_vel_84: float = 0.0

	var spring_vel_96: float = 0.0

	var spring_vel_101: float = 0.0

	var eight_phase_118: float = 0.0
	class Grounded extends HengoState:
		class Walking extends HengoState:
			var interval_237: float = 0.0
			func enter() -> void:
				interval_237 = 0.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"203", "8613291214389966227")
				_ref.ground_speed = 6.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"206", "8613291214389966227")
				_ref.gun_bob_gain = 0.01
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"209", "8613291214389966227")
				_ref.gun_bob_rate = 0.95

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"212", "8613291214389966227")
				var dir_212: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_212: Vector3 = (_ref.transform.basis * Vector3(dir_212.x, 0, dir_212.y)).normalized()
				_ref.velocity.x = world_212.x * _ref.speed
				_ref.velocity.z = world_212.z * _ref.speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"221", "8613291214389966227")
				if Input.is_key_pressed(KEY_SHIFT):
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"224", "8613291214389966227")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Walking", "go_to_Sprinting", "8613291214389966227")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("sprinting")
					return
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"225", "8613291214389966227")
				if ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"237", "8613291214389966227")
					interval_237 += delta
					if interval_237 >= 0.53:
						interval_237 = 0.0
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"239", "8613291214389966227")
						_ref.get_node("../Sfx/Step").play()
					else:
						pass
				else:
					pass

		class Sprinting extends HengoState:
			var interval_275: float = 0.0
			func enter() -> void:
				interval_275 = 0.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"241", "8613291214389966227")
				_ref.ground_speed = 10.5
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"244", "8613291214389966227")
				_ref.gun_bob_gain = 0.024
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"247", "8613291214389966227")
				_ref.gun_bob_rate = 1.5

			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"250", "8613291214389966227")
				var dir_250: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_250: Vector3 = (_ref.transform.basis * Vector3(dir_250.x, 0, dir_250.y)).normalized()
				_ref.velocity.x = world_250.x * _ref.sprint_speed
				_ref.velocity.z = world_250.z * _ref.sprint_speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"259", "8613291214389966227")
				if Input.is_key_pressed(KEY_SHIFT):
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"262", "8613291214389966227")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Sprinting", "go_to_Walking", "8613291214389966227")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("walking")
					return
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"263", "8613291214389966227")
				if ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"275", "8613291214389966227")
					interval_275 += delta
					if interval_275 >= 0.33:
						interval_275 = 0.0
						if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"277", "8613291214389966227")
						_ref.get_node("../Sfx/Step").play()
					else:
						pass
				else:
					pass

		func physics(delta) -> void:
			super(delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"194", "8613291214389966227")
			if _ref.is_on_floor():
				pass
			else:
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"196", "8613291214389966227")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Grounded", "go_to_Airborne", "8613291214389966227")
				_ref._STATE_CONTROLLER.current_state.change_sub_state("airborne")
				return
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"197", "8613291214389966227")
			if Time.get_ticks_msec() / 1000.0 - _ref.press_at_197 <= 0.2:
				_ref.press_at_197 = -99.0
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"200", "8613291214389966227")
				if _ref.is_on_floor():
					_ref.velocity.y = 8.0
			else:
				pass

		func _init(_p) -> void:
			super(_p)
			add_sub_state("walking", Walking.new(_p))
			add_sub_state("sprinting", Sprinting.new(_p))

		func enter() -> void:
			change_sub_state("walking")

	class Airborne extends HengoState:
		class Falling extends HengoState:
			var tap_at_301: float = -99.0
			var tap_down_301: bool = false
			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"292", "8613291214389966227")
				var dir_292: Vector2 = (Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down"))
				var world_292: Vector3 = (_ref.transform.basis * Vector3(dir_292.x, 0, dir_292.y)).normalized()
				_ref.velocity.x = world_292.x * _ref.air_speed
				_ref.velocity.z = world_292.z * _ref.air_speed
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"301", "8613291214389966227")
				var down_301: bool = Input.is_key_pressed(KEY_SHIFT)
				var pressed_301: bool = down_301 and not tap_down_301
				var paired_301: bool = false
				tap_down_301 = down_301
				if pressed_301:
					var now_301: float = Time.get_ticks_msec() / 1000.0
					paired_301 = now_301 - tap_at_301 <= 0.3
					tap_at_301 = -99.0 if paired_301 else now_301
				if paired_301:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"304", "8613291214389966227")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Falling", "go_to_Dashing", "8613291214389966227")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("dashing")
					return
				else:
					pass

			func enter() -> void:
				tap_at_301 = -99.0
				tap_down_301 = false

		class Dashing extends HengoState:
			var did_305: bool = false

			var window_334: float = 0.0
			func physics(delta) -> void:
				super(delta)
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"305", "8613291214389966227")
				if not did_305:
					did_305 = true
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"306", "8613291214389966227")
					var dir_306: Vector2 = ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")) if (((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length()) > 0.1) else (Vector2(0.0, -1.0)))
					var world_306: Vector3 = (_ref.transform.basis * Vector3(dir_306.x, 0, dir_306.y)).normalized()
					_ref.velocity.x = world_306.x * _ref.dash_speed
					_ref.velocity.z = world_306.z * _ref.dash_speed
				else:
					pass
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"334", "8613291214389966227")
				window_334 += delta
				if window_334 < 0.18:
					pass
				else:
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"336", "8613291214389966227")
					if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Dashing", "go_to_Falling", "8613291214389966227")
					_ref._STATE_CONTROLLER.current_state.current_sub_state.change_sub_state("falling")
					return

			func enter() -> void:
				did_305 = false
				window_334 = 0.0

		func enter() -> void:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"279", "8613291214389966227")
			_ref.air_speed = (_ref.ground_speed * 0.9)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"286", "8613291214389966227")
			_ref.gun_bob_gain = 0.0
			change_sub_state("falling")

		func physics(delta) -> void:
			super(delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"289", "8613291214389966227")
			if _ref.is_on_floor():
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"291", "8613291214389966227")
				if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Airborne", "go_to_Grounded", "8613291214389966227")
				_ref._STATE_CONTROLLER.current_state.change_sub_state("grounded")
				return
			else:
				pass

		func _init(_p) -> void:
			super(_p)
			add_sub_state("falling", Falling.new(_p))
			add_sub_state("dashing", Dashing.new(_p))

	func enter() -> void:
		_ref.look_on_35 = true
		_ref.look_move_35 = Vector2.ZERO
		spring_vel_39 = 0.0
		spring_vel_84 = 0.0
		spring_vel_96 = 0.0
		spring_vel_101 = 0.0
		_ref.key_on_191 = true
		_ref.key_hit_191 = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"27", "8613291214389966227")
		_ref.get_node("../Hud/Menu").visible = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"30", "8613291214389966227")
		_ref.paused = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"33", "8613291214389966227")
		Input.mouse_mode = Input.MOUSE_MODE_CAPTURED
		change_sub_state("grounded")

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"35", "8613291214389966227")
		var cam_35 = _ref.get_node("Roll/Cam")
		var pitch_35: float = deg_to_rad(85.0)
		_ref.rotate_y(-_ref.look_move_35.x * _ref.look_sense)
		cam_35.rotation.x = clamp(cam_35.rotation.x - _ref.look_move_35.y * _ref.look_sense, -pitch_35, pitch_35)
		_ref.look_move_35 = Vector2.ZERO
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"39", "8613291214389966227")
		spring_vel_39 += ((((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).x) * _ref.tilt) - _ref.roll_z) * 90.0 * delta
		spring_vel_39 *= clampf(1.0 - 14.0 * delta, 0.0, 1.0)
		_ref.roll_z += spring_vel_39 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"55", "8613291214389966227")
		_ref.get_node("Roll").rotation_degrees = (Vector3(0.0, 0.0, _ref.roll_z))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"62", "8613291214389966227")
		_ref.get_node("Roll").position = (Vector3(0.0, ((sin(Time.get_ticks_msec() / 1000.0 * 1.9 * TAU) * _ref.bob_power) * ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length())), 0.0))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"84", "8613291214389966227")
		spring_vel_84 += ((((Input.get_last_mouse_velocity()).x) * -1.8e-05) - _ref.sway_x) * 70.0 * delta
		spring_vel_84 *= clampf(1.0 - 13.0 * delta, 0.0, 1.0)
		_ref.sway_x += spring_vel_84 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"96", "8613291214389966227")
		spring_vel_96 += (0.0 - _ref.recoil) * 220.0 * delta
		spring_vel_96 *= clampf(1.0 - 22.0 * delta, 0.0, 1.0)
		_ref.recoil += spring_vel_96 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"101", "8613291214389966227")
		spring_vel_101 += ((_ref.gun_bob_gain * ((Input.get_vector(&"ui_left", &"ui_right", &"ui_up", &"ui_down")).length())) - _ref.gun_bob) * 40.0 * delta
		spring_vel_101 *= clampf(1.0 - 9.0 * delta, 0.0, 1.0)
		_ref.gun_bob += spring_vel_101 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"118", "8613291214389966227")
		eight_phase_118 = fmod(eight_phase_118 + _ref.gun_bob_rate * delta, 1.0)
		var wire_118_side = sin(eight_phase_118 * TAU) * _ref.gun_bob
		var wire_118_rise = sin(eight_phase_118 * TAU * 2.0) * _ref.gun_bob * 0.5
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"121", "8613291214389966227")
		if Input.is_mouse_button_pressed(MOUSE_BUTTON_RIGHT):
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"124", "8613291214389966227")
			_ref.aim = move_toward(_ref.aim, 1.0, 6.0 * delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"128", "8613291214389966227")
			if 6.0 > 0.0:
				_ref.get_node("Roll/Cam").fov = lerpf(_ref.get_node("Roll/Cam").fov, 48.0, clampf(6.0 * delta, 0.0, 1.0))
			else:
				_ref.get_node("Roll/Cam").fov = 48.0
		else:
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"132", "8613291214389966227")
			_ref.aim = move_toward(_ref.aim, 0.0, 6.0 * delta)
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"136", "8613291214389966227")
			if 6.0 > 0.0:
				_ref.get_node("Roll/Cam").fov = lerpf(_ref.get_node("Roll/Cam").fov, 75.0, clampf(6.0 * delta, 0.0, 1.0))
			else:
				_ref.get_node("Roll/Cam").fov = 75.0
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"140", "8613291214389966227")
		_ref.get_node("Roll/Cam/Gun").position = (lerp((Vector3(((0.31350517 + _ref.sway_x) + (wire_118_side)), (-0.22229338 + (wire_118_rise)), (_ref.gun_home + _ref.recoil))), ((_ref.get_node("Roll/Cam/AimPose").get_indexed('position')) + (Vector3(((wire_118_side) * 0.45), ((wire_118_rise) * 0.45), _ref.recoil))), _ref.aim))
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"186", "8613291214389966227")
		_ref.velocity.y -= 24.0 * delta
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"189", "8613291214389966227")
		_ref.move_and_slide()
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"191", "8613291214389966227")
		if _ref.key_hit_191:
			_ref.key_hit_191 = false
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Playing", "go_to_Paused", "8613291214389966227")
			_ref._STATE_CONTROLLER.change_state("paused")
			return
		else:
			pass

	func exit() -> void:
		super()
		_ref.look_on_35 = false
		_ref.key_on_191 = false

	func _init(_p) -> void:
		super(_p)
		add_sub_state("grounded", Grounded.new(_p))
		add_sub_state("airborne", Airborne.new(_p))

class Paused extends HengoState:
	func enter() -> void:
		_ref.key_on_345 = true
		_ref.key_hit_345 = false
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"337", "8613291214389966227")
		_ref.get_node("../Hud/Menu").visible = true
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"340", "8613291214389966227")
		Input.mouse_mode = Input.MOUSE_MODE_VISIBLE
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"342", "8613291214389966227")
		_ref.paused = true

	func physics(delta) -> void:
		super(delta)
		if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_action(&"345", "8613291214389966227")
		if _ref.key_hit_345:
			_ref.key_hit_345 = false
			if _ref.get_instance_id() == HengoDebugger.state_targets.get("8613291214389966227", -1): HengoDebugger.trace_state_transition("Paused", "go_to_Playing", "8613291214389966227")
			_ref._STATE_CONTROLLER.change_state("playing")
			return
		else:
			pass

	func exit() -> void:
		super()
		_ref.key_on_345 = false
