# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

var target = Vector2(576, 324)  
 
var click_on_47: bool = false
var clicked_47: bool = false
var _fn_3_pick_target_point: Vector2 = Vector2(0, 0)
var _mc_17_speed = 720.0
var _mc_17_seconds = 0.35
var _mc_20_speed = 120.0
var _mc_20_seconds = 1.2

var _STATE_CONTROLLER = HengoStateController.new(self)

const _EVENTS = {}


func _init() -> void:
	_STATE_CONTROLLER.set_states({
		playing=Playing.new(self),
	})


func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("playing")



func trigger_event(_event: StringName) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])


func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

func _input(event: InputEvent) -> void:
	if click_on_47 and event is InputEventMouseButton and event.button_index == MOUSE_BUTTON_LEFT:
		if event.pressed and not event.double_click:
			clicked_47 = true

func fn_pick_target(max_distance: float = 300.0) -> StringName:
	var from_23 = self.get_global_mouse_position()
	var to_23 = self.position
	var near_23: bool = absf(float(from_23) - float(to_23)) <= max_distance if typeof(from_23) in [TYPE_INT, TYPE_FLOAT] else from_23.distance_to(to_23) <= max_distance
	if near_23:
		self._fn_3_pick_target_point = self.get_global_mouse_position()
		return &'pick_target_near'
	else:
		self._fn_3_pick_target_point = self.get_global_mouse_position()
		return &'pick_target_far'
	return &''

class Playing extends HengoState:
	class Idle extends HengoState:
		pass

	class Aim extends HengoState:
		func enter() -> void:
			match _ref.fn_pick_target(300.0):
				&'pick_target_near':
					_ref.target = (_ref._fn_3_pick_target_point)
					_ref._STATE_CONTROLLER.current_state.change_sub_state("walk")
					return
				&'pick_target_far':
					_ref.position = (_ref._fn_3_pick_target_point)
					_ref._STATE_CONTROLLER.current_state.change_sub_state("slow_spin")
					return

	class Walk extends HengoState:
		func update(delta) -> void:
			super(delta)
			_ref.position = lerp(_ref.position, _ref.target, 0.1)
			var from_64 = _ref.position
			var to_64 = _ref.target
			var near_64: bool = absf(float(from_64) - float(to_64)) <= 8.0 if typeof(from_64) in [TYPE_INT, TYPE_FLOAT] else from_64.distance_to(to_64) <= 8.0
			if near_64:
				_ref._STATE_CONTROLLER.current_state.change_sub_state("quick_spin")
				return
			else:
				pass

	class QuickSpin extends HengoState:
		class Spinning extends HengoState:
			var wait_42_17: float = 0.0
			func update(delta) -> void:
				super(delta)
				_ref.rotation_degrees += _ref._mc_17_speed * delta
				wait_42_17 += delta
				if wait_42_17 >= _ref._mc_17_seconds:
					_ref._STATE_CONTROLLER.current_state.change_sub_state("idle")
					return

			func exit() -> void:
				super()
				_ref.rotation_degrees = 0.0

			func enter() -> void:
				wait_42_17 = 0.0

		func _init(_p) -> void:
			super(_p)
			add_sub_state("spinning", Spinning.new(_p))

		func enter() -> void:
			change_sub_state("spinning")

	class SlowSpin extends HengoState:
		class Spinning extends HengoState:
			var wait_42_20: float = 0.0
			func update(delta) -> void:
				super(delta)
				_ref.rotation_degrees += _ref._mc_20_speed * delta
				wait_42_20 += delta
				if wait_42_20 >= _ref._mc_20_seconds:
					_ref._STATE_CONTROLLER.current_state.change_sub_state("idle")
					return

			func exit() -> void:
				super()
				_ref.rotation_degrees = 0.0

			func enter() -> void:
				wait_42_20 = 0.0

		func _init(_p) -> void:
			super(_p)
			add_sub_state("spinning", Spinning.new(_p))

		func enter() -> void:
			change_sub_state("spinning")

	func update(delta) -> void:
		super(delta)
		if _ref.clicked_47:
			_ref.clicked_47 = false
			_ref._STATE_CONTROLLER.current_state.change_sub_state("aim")
			return
		else:
			pass

	func enter() -> void:
		_ref.click_on_47 = true
		_ref.clicked_47 = false
		change_sub_state("idle")

	func exit() -> void:
		super()
		_ref.click_on_47 = false

	func _init(_p) -> void:
		super(_p)
		add_sub_state("idle", Idle.new(_p))
		add_sub_state("aim", Aim.new(_p))
		add_sub_state("walk", Walk.new(_p))
		add_sub_state("quick_spin", QuickSpin.new(_p))
		add_sub_state("slow_spin", SlowSpin.new(_p))
